version: 2
jobs:
  build:
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: "node --version"
      - run: echo "A first hello"
      - run: "ls"
      - run: "touch .cache"
      - run: "env"